### ISSUE TITLE
Add full support for optional positional paramaters.

### ISSUE THREAD

**Issue by ericjaystevens** [ericjaystevens/slashparse#16]
If a positional parameter is optional the default value will be used if an underscore is passed.

so for a command defined as such

```
name: Print
description: Echos back what you type.
arguments:
  - name: text
    argtype: quoted text
    optional: true
    defaultValue: Much default wow.
    position: 1
 - name: effect
   argtype: enum
   options: allcaps, camelcase, leetspeak, shouting
   position: 2
```
the following command should be equivalent

```
/print "Much default wow." allcaps
/print _ allcaps
```

and properly implemented would return ```MUCH DEFAULT WOW.```
