### ISSUE TITLE
Add support for remaining text argtype

### ISSUE THREAD

**Issue by ericjaystevens** [ericjaystevens/slashparse#18]
A slash definition like so 

```
name: groupmsg
description: sends a message to a group
arguments:
  - name: usernames
    argtype: word
    description: Users you want to send text to 
    position: 1
 - name: message
    argtype: remaining text
    description: message to send to the group
    position: 2
```

the command 

```
/groupmsg ericjaystevens,gabejackson,santa Do you want to build a snowman?
```

Should take ```ericjaystevens,gabejackson,santa``` as the first argument and ```Do you want to build a snowman?``` as the second.
